---
AWSTemplateFormatVersion: '2010-09-09'
Parameters: 
  myJenkinsVolume: 
    Description: EBS Volume with jenkins home
    Type: "AWS::EC2::Volume::Id"
  myKeyPair: 
    Description: Key pair for jenkins ec2 instance
    Type: "AWS::EC2::KeyPair::KeyName"
Resources:
  MyEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-0528a5175983e7f28"
      InstanceType: "t2.small"
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet: 
            - !Ref InstanceSecurityGroup
          SubnetId: !Ref PublicSubnet1
      UserData:
        Fn::Base64:
          Fn::Sub:
            |
            #!/bin/bash
            aws ec2 attach-volume --volume-id ${myJenkinsVolume} --instance-id $(ec2-metadata --instance-id | cut -d " " -f 2) --device /dev/xvdf --region us-west-2
            aws ec2 wait volume-in-use --volume-ids ${myJenkinsVolume} --region us-west-2
            sleep 5
            sudo yum install git -y
            mkdir /var/lib/jenkins
            mount /dev/xvdf /var/lib/jenkins/
            sudo yum remove java-1.7.0-openjdk
            sudo yum install java-1.8.0 -y
            sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
            sudo rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
            sudo yum install jenkins -y
            chmod 777 /var/lib/jenkins/
            sudo service jenkins start
      IamInstanceProfile: !Ref RootInstanceProfile
      KeyName: !Ref myKeyPair
  RootRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
  RootInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref RootRole
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
                    
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Public Subnet (AZ1)

  NatGateway1EIP:
    Type: AWS::EC2::EIP
    DependsOn: InternetGatewayAttachment
    Properties:
      Domain: vpc

  NatGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGateway1EIP.AllocationId
      SubnetId: !Ref PublicSubnet1
      
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Public Routes

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
      
  InternetGateway:
    Type: AWS::EC2::InternetGateway

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow http to client host
        VpcId:
           Ref: VPC
        SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
          
  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
Outputs:
  PublicIp:
    Description: "Server's PublicIp Address"
    Value: !Sub 'http://${MyEC2Instance.PublicIp}:8080'
  SecurityGroup:
    Description: "Server's security group"
    Value: !Ref InstanceSecurityGroup
